### ISSUE TITLE
Exporting coordinates 

### ISSUE THREAD

**Issue by DavisAndn** [YsoSirius/windfarmGA#16]
Firstly, awesome project. Even as a beginner to R, I was able to follow through and learnt a lot from this model. 
How do you export the coordinates to a CSV or similar file though? The results matrix is very convoluted to work with

**Comment by trafficonese** [comment]
Hey thank you very much, I'm glad you find it helpful.

True, the resulting matrix contains a lot of information and very little documentation. Plus the column names are a mixture of German + English, I am very bad at naming things indeed :)

If you want to see the result+coordinates of the windfarm with the highest energy outcome you can do:
```
res <- plot_result(result, Polygon1, best = 1, plotEn = 1, topographie = FALSE, Grid = Grid[[2]])
res
```
This will plot the result aswell.

If you don't want to plot it, you can search the resulting matrix like this:
`result[,"bestPaEn"][which.max(unlist(lapply(result[,"bestPaEn"], function(x) unique(x[,"Parkfitness"]))))]`

**result[,"bestPaEn"]** contains a list of the windpark with the highest energy outcome per generation (_bestPaEn = best park energy_)
**result[,"bestPaEf"]** contains a list of windparks with the highest efficiency (_bestPaEf = best park efficiency_). 

The 2 lists will be identical if no terrain model was used.

**Comment by DavisAndn** [comment]
> `result[,"bestPaEn"][which.max(unlist(lapply(result[,"bestPaEn"], function(x) unique(x[,"Parkfitness"]))))]`

Works like a charm thank you very much! 

Just another small question, When I try use the genetic algorithm(), I get an error saying projection not found, but in windfarmGA() it automatically says "Polygon is not projected. Lambert Azimuthal Equal Area Projection is used." Why is that? 
I'm using a simple square as the shapefile with no terrain inputs. 
________________________________________________________________________________________________________________________________________
Edit: After running library(rgdal), I was able to use the genetic algorithm by 
```
Projection <- "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000
+ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
proj4string(Polygon1) <- CRS(Projection)
```
as you mentioned in the readme.md. 
I'm not sure what this does though. Is the surface still a plane after this?

**Comment by DavisAndn** [comment]
The efficiency isn't rising with every generation too. Am I doing something wrong? 
![Capture](https://user-images.githubusercontent.com/33925238/93660545-bc8da480-fa6d-11ea-9226-bdd530b5ed89.PNG)

**Comment by trafficonese** [comment]
Yes, a lot has changed in how the underlying libraries deal with reference systems. I haven't had time to look into the problem.

The efficiency does not necessarily have to increase with each generation. The recombination and mutation could result in worse wind farms than the previous generation, but should definitely increase in the long run. I've also tried adding the best current generation wind farm to the next, but instead decided to use another fallback. If no better energy result has been found for 20 generations, the wind farms with the previously highest energy result are again added to the population.

Anyway, I suggest you run the algorithm for ~100 generations and then plot this graph again.

**Comment by trafficonese** [comment]
@DavisAndhersonF, did you manage to increase efficiency with more iterations?

**Comment by DavisAndn** [comment]
Unfortunately not. I was not able to spend as much time on it as I would have liked to due to other commitments. I will try to in a couple of weeks

**Comment by trafficonese** [comment]
If you try again and still dont see any improvement, please reopen this issue.
Or you could contact me via email directly and send me the Shapefile and Wind-Data that you're using and I will have a look at it.
