### ISSUE TITLE
unreliable results of cansee function

### ISSUE THREAD

**Issue by MrEtmAr** [YsoSirius/windfarmGA#17]
Hi
first I want to thank you for this great package, it has been very helpful to me
I have an issue with unreliable LOS result with respect to my raster
while trying to understand it I got to the "cansee" function:

```
function (r, xy1, xy2, h1 = 0, h2 = 0, reso) 
{
  xyz = rasterprofile(r, xy1, xy2, reso)
  np = length(xyz[, 1]) - 1
  h1 = xyz[, "z"][1] + h1
  h2 = xyz[, "z"][np] + h2
  hpath = h1 + (0:np) * (h2 - h1)/np
  invisible(!any(hpath < xyz[, "z"], na.rm = TRUE))
}
```
I want to ask about the " np = length(xyz[, 1]) - 1" line.  whenever looking on an increasing slope this produces an "invisible" result because the terminal point (xyz(length(xyz)) is by definition higher than its counterpart on the hpath (  h2 = xyz[, "z"][np] + h2 ).
can you verify my suspicion?

**Comment by trafficonese** [comment]
I think you are right there seems to be a bug. 
The height of Pt2 (`h2`) seems to be wrong because it receives the height of the penultimate point on the path and not the last point. 

So either I change `np = length(xyz[, 1]) - 1` to `np = length(xyz[, 1])` or 
the h2-line changes to `h2 = xyz[, "z"][np + 1] + h2`.
I'll check it out.

I am also thinking of including a `plot` argument to `cansee` which would create a plot like this for every point-combination. What do you say?

![grafik](https://user-images.githubusercontent.com/35805180/102052701-c7df3a80-3de6-11eb-9e04-c88fcc6b17d9.png)

**Comment by MrEtmAr** [comment]
Hi
Both the corrections can do the job, please let me know when you include them so I can update may code.
Regarding the plot option, to me, it seems a good addition. Actually, that is exactly the method I used to identify the bug. (Only I combined it with the "locator" function from R "graphics" library. I am specifying an antenna and I can check the line of sight to any point I choose on a map using this function).

In the last graph, I  would also specify the additional height of pt1 and pt2.
Just to understand, on the "cansee" plot, what does the "TRUE / FALSE"  on each point mean? do you actually calculate the line of sight to each point within that line or are these results calculated with respect to the last point? 
- if the latter is the answer, I would not put them on the graph, they might be misleading
- if the former, you can optimize the code significantly by checking the LOS to all points on any geometric line instead of evaluating LOS for all grid points independently.

Eitam

**Comment by trafficonese** [comment]
Great, I'll add the plotting functionality. I think the extra height offsets are already included in the second plot, but I can also add them to a legend and add them as vertical lines. I am also thinking of coloring the visibility track.

The TRUE/FALSE indicates if the terrain is higher than the visibility track. So if any point is TRUE, then the Points are not visible to each other. Maybe I should switch TRUE to FALSE and FALSE to TRUE, that would make more sense if we're talking about visibility. Then any FALSE indicates that no visibility is given.

The LOS (blue line in plot 2) is just calculated between Pt1 and Pt2, so it's a straight line.

**Comment by MrEtmAr** [comment]
Hi
Sorry for taking so long to check these corrections.
As far as I can see the code runs well when  h1 is a numeric vector
Still, the line of sight results are wrong (according to my tests), the reason is the cansee function:
Your version:
`function (r, xy1, xy2, h1 = 0, h2 = 0, reso) 
{
  xyz = rasterprofile(r, xy1, xy2, reso)
  np = length(xyz[, 1]) - 1
  h1 = xyz[, "z"][1] + h1
  h2 = xyz[, "z"][np] + h2
  hpath = h1 + (0:np) * (h2 - h1)/np
  invisible(!any(hpath < xyz[, "z"], na.rm = TRUE))
}
`
still takes the height of point before the last one (`h2 = xyz[, "z"][np] + h2` )

I use a local version:
`cansee <- function (r, xy1, xy2, h1 = 0, h2 = 0, reso) 
{
  xyz = rasterprofile(r, xy1, xy2, reso)
  np = length(xyz[, 1]) 
  h1 = xyz[, "z"][1] + h1
  h2 = xyz[, "z"][np] + h2
  hpath = h1 + (0:(np-1)) * (h2 - h1)/(np-1)
  invisible(!any(hpath < xyz[, "z"], na.rm = TRUE))
}`

another topic that I have changed is that I organize all results as a single raster, to mee it makes it easier to save, present, and read.
Hope that this review helps

Eitam
