### ISSUE TITLE
Cansee still provides unreliable results

### ISSUE THREAD

**Issue by MrEtmAr** [YsoSirius/windfarmGA#24]
Hi
Sorry for taking so long to check these corrections.
As far as I can see the code runs well when  h1 is a numeric vector
Still, the line of sight results are wrong (according to my tests), the reason is the cansee function:
Your version:
`function (r, xy1, xy2, h1 = 0, h2 = 0, reso) 
{
  xyz = rasterprofile(r, xy1, xy2, reso)
  np = length(xyz[, 1]) - 1
  h1 = xyz[, "z"][1] + h1
  h2 = xyz[, "z"][np] + h2
  hpath = h1 + (0:np) * (h2 - h1)/np
  invisible(!any(hpath < xyz[, "z"], na.rm = TRUE))
}
`
still takes the height of point before the last one (`h2 = xyz[, "z"][np] + h2` )

I use a local version:
`cansee <- function (r, xy1, xy2, h1 = 0, h2 = 0, reso) 
{
  xyz = rasterprofile(r, xy1, xy2, reso)
  np = length(xyz[, 1]) 
  h1 = xyz[, "z"][1] + h1
  h2 = xyz[, "z"][np] + h2
  hpath = h1 + (0:(np-1)) * (h2 - h1)/(np-1)
  invisible(!any(hpath < xyz[, "z"], na.rm = TRUE))
}`

another topic that I have changed is that I organize all results as a single raster, to mee it makes it easier to save, present, and read.
Hope that this review helps

Eitam

_Originally posted by @MrEtmAr in https://github.com/YsoSirius/windfarmGA/issues/17#issuecomment-761878946_

**Comment by trafficonese** [comment]
Hey,
thanks for double checking!
Could you try the current github version?
I think that should be fixed now.

**Comment by trafficonese** [comment]
The new v4.0 uses the function `terra::viewshed` which should be correct.
