### ISSUE TITLE
Library fail to load

### ISSUE THREAD

**Issue by tristanfabregas** [YsoSirius/windfarmGA#25]
First of all, thank you for your great work on this package.
For a week, I can no longer load the library (on Mac and Windows), the following error appears in the console:

`library(windfarmGA)`
returns:
> Error: package or namespace load failed for ‘windfarmGA’:
 object ‘hexgrid’ is not exported by 'namespace:spatstat'

Do you know how to fix that ?
Regards

**Comment by YsoSirius** [comment]
Hey,
Did you try with the latest windfarmGA release or with the current github version?
I know that spatstat changed substantially but the latest version shouldn't require that package anymore.

**Comment by tristanfabregas** [comment]
I've tried both with same results

**Comment by tristanfabregas** [comment]
I've tried both with same results

**Comment by trafficonese** [comment]
Could you please try again installing the current github version?

**Comment by tristanfabregas** [comment]
Problem fixed, thank you very much

**Comment by trafficonese** [comment]
Awesome!
I will try to upload it to Cran within the next weeks.. I just realized recently that it was removed..
