### ISSUE TITLE
Theory of Masking the turbines.

### ISSUE THREAD

**Issue by SamAct** [YsoSirius/windfarmGA#3]
Hello,
Would you kindly explain how the exact location of a turbine is masked into the elevation raster data?
I understand the way a polygon is masked but since we are not supplying the exact locations in latitude & longitude of the turbines in the input (Or are we?) how are they masked. Yet you seem to start with a  reference shape of the turbines on the farm in Case 2 in your study.

Thanks for your help. Kindly clear my confusion.

**Comment by YsoSirius** [comment]
Hey Sam,
Im not really sure what you mean by "masked", but ill try to answer your question. :)
So first of all, the goal of the algorithm is to find the best locations for all turbines, so clearly they are not known in advance. If you knew them, the algorithm would be obsolet. :P 

The possible locations of turbines are calculated by the algorithm itself. The polygon is divided into rectangular or hexagonal grid cells, where the size of the squares/heaxogons depends on the rotor radius and a certain factor. The centroids of those grid cells represent the possible locations of the turbines. From all those possible locations, the algorithm tries to find the best combination of them.

For all those turbine locations, elevation data is extracted from an SRTM dataset, which is then used to estimate for instance air density for each turbine. But the elevation does not impact the wake effect model. The wake effect model is therefore not a 3D model, it still calculates wake effects in 2D. So for example; a turbine which is directly behind another turbine but actually 200 meters higher, will still have a wake influence of 100%.

The elevation data is just used for air density, surface roughness, wind speed and wake decay estimations.

I hope to have answered your question. If not, let me know!

**Comment by SamAct** [comment]
Great, that's a good explanation. Now if I were to plot the final turbine locations that are used to calculate the turbines annual energy, which parameter I should look for in the code?
I intend to change it to true turbine location as seen in real world maps to see the difference it would make in output.

**Comment by YsoSirius** [comment]
For now, I'm not calculating annual energy production and the resulting energy outputs will be per hour. So you would have to multiply them by the expected annual working hours. This would go in the calculateEn() or maybe in the fitness() function, if you want to change the code deep down. ;)

You could also only modify the energy outputs in the plotting functions.
To plot the results on real maps I actually have 3 functions included. Look at these functions and their examples: GooglePlot(), GoogleChromePlot() and leafPlot().

GooglePlot is is a static plot, but you'll have a satellite image background.
GoogleChromePlot will dynamically plot the layout in Chrome, using also satellite imagery as background.
The leafPlot is probably the most interesting function for you. For now it only has the basemaps OSM and Toner, so you would have to add some satellite image background.

**Comment by SamAct** [comment]
yes, annual energy might as well require Weibull and power curves. That's for later. 
But the thing is I could not find the turbine location values that you use to plot in googleplot or Chrome plot in your study, is it from function(x,y)? For example, as you have mentioned:
while calculating the distance between two turbines coordinates. 
> #' x=c(200,100)
> #' y=c(1000,2000)
> #' euc.dist(x,y)

Does the end result from GA stored in x, y as well? Edit: is it allCoords function?

**Comment by YsoSirius** [comment]
If you load the example data in the package
`load(file = system.file("extdata/resultrect.rda", package = "windfarmGA"))`
you get a resulting matrix of a genAlgo or windfarmGA function call. When you look at the head info you will see the column bestPaEn and bestPaEf (column 2&3), which store the information of the best individual for every generation regarding energy output (bestPaEn) and efficiency output (bestPaEf).
`head(resultrect)`
And the information of the best energy output of the first round for example can be called with
`str(resultrect[,"bestPaEn"][[1]])`
where you can find the X and Y coordinates of the turbines of that layout.

**Comment by SamAct** [comment]
Great was of tremendous help. Let me get back to you with what I find. Thanks again!

**Comment by YsoSirius** [comment]
You're welcome!
And in case you wondered, the projection of the turbine coordinates in the resulting matrix is EPSG:3035. So for now its only accurately working for places in Europe. 
All the best!
